services:
    uniregistry.repository.edge:
        class: AppBundle\Repository\EdgeRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle:Edge

    uniregistry.adapter.entity:
        class: AppBundle\Adapter\EntityAdapter

    uniregistry.parser.graph.xml:
        class: Uniregistry\Parser\XmlGraphParser
        arguments:
            - "@jms_serializer"

    uniregistry.parser.query.json:
        class: Uniregistry\Parser\JsonQueryParser
        arguments:
            - "@jms_serializer"

    uniregistry.query.render.html:
        class: Uniregistry\Query\Render\HtmlQueryRender
        arguments:
            - "@uniregistry.repository.edge"
            - "@twig.loader.string"

    uniregistry.query.render.json:
        class: Uniregistry\Query\Render\JsonQueryRender
        arguments:
            - "@uniregistry.repository.edge"

    jms.serializer.post_deserialize_subscriber:
        class: Uniregistry\Listener\Serializer\PostDeserializeSubscribe
        tags:
            - { name: jms_serializer.event_subscriber }

    jms.serializer.pre_deserialize_subscriber:
        class: Uniregistry\Listener\Serializer\PreDeserializeSubscribe
        tags:
            - { name: jms_serializer.event_subscriber }

    twig.loader.string:
        class: AppBundle\Twig\TwigLoaderString